server:
  port: 8001

spring:
  application:
    name: rabbitmq-provider

  #配置rabbitmq服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #消息确认配置

    #确认消息到达exchange
    publisher-confirms: true
    #确认消息到达Queuel
    publisher-returns: true
    #配置消费者的每次获取数以及确认方式
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual